swagger: "2.0"
info:
  title: allaboutapps.dev/aw/go-starter
  version: 0.1.0
paths:
  /api/v1/wss/stream:
    get:
      description: |-
        key - (scope) - description
        test - (app) - text description
        testUser - (user) - text description
      tags:
        - wss
      summary: Test Endpoint for wss streams
      parameters:
        - $ref: "../definitions/wss.yml#/parameters/wssTokenParam"
      operationId: GetWSSStreamRoute
      responses:
        "200":
          description: GetStreamResponse
          schema:
            $ref: ../definitions/sse.yml#/definitions/GetStreamResponse
  /api/v1/wss/token:
    get:
      description: endpoint for wss token
      tags:
        - wss
      summary: Endpoint for wss token
      operationId: GetWSSTokenRoute
      responses:
        "200":
          description: GetWSSTokenResponse
          schema:
            $ref: ../definitions/sse.yml#/definitions/GetWSSTokenResponse
