swagger: "2.0"
info:
  title: allaboutapps.dev/aw/go-starter
  version: 0.1.0
paths: {}
definitions:
  GetStreamResponse:
    type: string
    example: channel1
  GetWSSTokenResponse:
    type: object
    required:
      - token
    properties:
      token:
        type: string
        format: uuid
        example: "f0f8e8f8-f0f8-f0f8-f0f8-f0f8f0f8f0f8"

parameters:
  valueParam:
    required: true
    type: string
    in: path
    name: value
    description: Value
  channelList:
    type: array
    items:
      type: string
    in: query
    name: channelList
    description: Channel List
    required: true
